version: 0.0
os: linux

files:
  - source: application-code/web-tier/build
    destination: /var/www/html
  - source: application-code/app-tier
    destination: /home/ubuntu/backend
  - source: scripts
    destination: /home/ubuntu/scripts

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
