version: 0.2

phases:
    commands:
      - echo Installing frontend dependencies...
      - cd application-code/web-tier
    

  build:
    commands:
      - cd application-code/web-tier
      - docker build -t web-tier .


